<?php

use Illuminate\Database\Seeder;

class SlidersImagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sliders_images')->delete();
        
        \DB::table('sliders_images')->insert(array (
            0 => 
            array (
                'sliders_id' => 1,
                'sliders_title' => 'ewgrege',
                'sliders_url' => '#',
                'carousel_id' => 5,
                'sliders_image' => '16',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2020-07-08 00:00:00',
                'date_added' => '2019-09-08 18:44:49',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            1 => 
            array (
                'sliders_id' => 2,
                'sliders_title' => 'frgergege',
                'sliders_url' => '#',
                'carousel_id' => 5,
                'sliders_image' => '17',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2020-10-14 00:00:00',
                'date_added' => '2019-09-08 18:45:10',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            2 => 
            array (
                'sliders_id' => 3,
                'sliders_title' => 'dgdthrh',
                'sliders_url' => '#',
                'carousel_id' => 5,
                'sliders_image' => '18',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2019-09-18 00:00:00',
                'date_added' => '2019-09-08 18:45:40',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            3 => 
            array (
                'sliders_id' => 4,
                'sliders_title' => 'sdasdasdass',
                'sliders_url' => '',
                'carousel_id' => 1,
                'sliders_image' => '111',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2020-07-15 00:00:00',
                'date_added' => '2019-09-10 08:26:49',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            4 => 
            array (
                'sliders_id' => 5,
                'sliders_title' => 'fdsfds',
                'sliders_url' => '',
                'carousel_id' => 1,
                'sliders_image' => '111',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2020-08-14 00:00:00',
                'date_added' => '2019-09-10 08:27:04',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            5 => 
            array (
                'sliders_id' => 6,
                'sliders_title' => 'fsfsfsfss',
                'sliders_url' => '',
                'carousel_id' => 1,
                'sliders_image' => '111',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2030-01-30 00:00:00',
                'date_added' => '2019-09-10 08:27:21',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            6 => 
            array (
                'sliders_id' => 7,
                'sliders_title' => 'fdssdfsf',
                'sliders_url' => '',
                'carousel_id' => 2,
                'sliders_image' => '108',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2020-11-19 00:00:00',
                'date_added' => '2019-09-10 08:28:18',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            7 => 
            array (
                'sliders_id' => 8,
                'sliders_title' => 'dasdada',
                'sliders_url' => '',
                'carousel_id' => 2,
                'sliders_image' => '108',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2021-07-14 00:00:00',
                'date_added' => '2019-09-10 08:28:31',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            8 => 
            array (
                'sliders_id' => 9,
                'sliders_title' => 'dad',
                'sliders_url' => '',
                'carousel_id' => 2,
                'sliders_image' => '108',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2020-06-24 00:00:00',
                'date_added' => '2019-09-10 08:28:49',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            9 => 
            array (
                'sliders_id' => 10,
                'sliders_title' => 'daadsd',
                'sliders_url' => '',
                'carousel_id' => 3,
                'sliders_image' => '110',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2021-10-20 00:00:00',
                'date_added' => '2019-09-10 08:29:41',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            10 => 
            array (
                'sliders_id' => 11,
                'sliders_title' => 'sasdasd',
                'sliders_url' => '',
                'carousel_id' => 3,
                'sliders_image' => '110',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2020-07-15 00:00:00',
                'date_added' => '2019-09-10 08:29:58',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            11 => 
            array (
                'sliders_id' => 12,
                'sliders_title' => 'ewef',
                'sliders_url' => '',
                'carousel_id' => 3,
                'sliders_image' => '110',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2021-07-15 00:00:00',
                'date_added' => '2019-09-10 08:30:13',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            12 => 
            array (
                'sliders_id' => 13,
                'sliders_title' => 'fvtrgr',
                'sliders_url' => '',
                'carousel_id' => 4,
                'sliders_image' => '109',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2021-06-15 00:00:00',
                'date_added' => '2019-09-10 12:29:16',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            13 => 
            array (
                'sliders_id' => 14,
                'sliders_title' => 't4tt',
                'sliders_url' => '',
                'carousel_id' => 4,
                'sliders_image' => '109',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2021-10-25 00:00:00',
                'date_added' => '2019-09-10 12:29:33',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            14 => 
            array (
                'sliders_id' => 15,
                'sliders_title' => '4t4t4',
                'sliders_url' => '',
                'carousel_id' => 4,
                'sliders_image' => '109',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '2022-07-07 00:00:00',
                'date_added' => '2019-09-10 12:29:50',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 1,
            ),
            15 => 
            array (
                'sliders_id' => 16,
                'sliders_title' => 'ewgrege',
                'sliders_url' => '#',
                'carousel_id' => 5,
                'sliders_image' => '16',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            16 => 
            array (
                'sliders_id' => 17,
                'sliders_title' => 'frgergege',
                'sliders_url' => '#',
                'carousel_id' => 5,
                'sliders_image' => '17',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            17 => 
            array (
                'sliders_id' => 18,
                'sliders_title' => 'dgdthrh',
                'sliders_url' => '#',
                'carousel_id' => 5,
                'sliders_image' => '18',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            18 => 
            array (
                'sliders_id' => 19,
                'sliders_title' => 'sdasdasdass',
                'sliders_url' => '',
                'carousel_id' => 1,
                'sliders_image' => '111',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            19 => 
            array (
                'sliders_id' => 20,
                'sliders_title' => 'fdsfds',
                'sliders_url' => '',
                'carousel_id' => 1,
                'sliders_image' => '111',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            20 => 
            array (
                'sliders_id' => 21,
                'sliders_title' => 'fsfsfsfss',
                'sliders_url' => '',
                'carousel_id' => 1,
                'sliders_image' => '111',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            21 => 
            array (
                'sliders_id' => 22,
                'sliders_title' => 'fdssdfsf',
                'sliders_url' => '',
                'carousel_id' => 2,
                'sliders_image' => '108',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            22 => 
            array (
                'sliders_id' => 23,
                'sliders_title' => 'dasdada',
                'sliders_url' => '',
                'carousel_id' => 2,
                'sliders_image' => '108',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            23 => 
            array (
                'sliders_id' => 24,
                'sliders_title' => 'dad',
                'sliders_url' => '',
                'carousel_id' => 2,
                'sliders_image' => '108',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            24 => 
            array (
                'sliders_id' => 25,
                'sliders_title' => 'daadsd',
                'sliders_url' => '',
                'carousel_id' => 3,
                'sliders_image' => '110',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            25 => 
            array (
                'sliders_id' => 26,
                'sliders_title' => 'sasdasd',
                'sliders_url' => '',
                'carousel_id' => 3,
                'sliders_image' => '110',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            26 => 
            array (
                'sliders_id' => 27,
                'sliders_title' => 'ewef',
                'sliders_url' => '',
                'carousel_id' => 3,
                'sliders_image' => '110',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            27 => 
            array (
                'sliders_id' => 28,
                'sliders_title' => 'fvtrgr',
                'sliders_url' => '',
                'carousel_id' => 4,
                'sliders_image' => '109',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            28 => 
            array (
                'sliders_id' => 29,
                'sliders_title' => 't4tt',
                'sliders_url' => '',
                'carousel_id' => 4,
                'sliders_image' => '109',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
            29 => 
            array (
                'sliders_id' => 30,
                'sliders_title' => '4t4t4',
                'sliders_url' => '',
                'carousel_id' => 4,
                'sliders_image' => '109',
                'sliders_group' => '',
                'sliders_html_text' => '',
                'expires_date' => '0000-00-00 00:00:00',
                'date_added' => '2019-10-11 06:51:42',
                'status' => 1,
                'type' => 'product',
                'date_status_change' => NULL,
                'languages_id' => 2,
            ),
        ));
        
        
    }
}